export const SET_LOADING = 'SET_LOADING'
export const SET_SUMMONER = 'SET_SUMMONER'
export const SET_MATCHES = 'SET_MATCHES'
export const SET_MATCH = 'SET_MATCH'
export const HANDLE_SEARCH = 'HANDLE_SEARCH'
